os: linux
dist: xenial

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8-dev"

branches:
  only:
    - master

install:
  - set -o errexit; source .travis/04_install.sh
script:
  - set -o errexit; source .travis/06_script.sh

cache:
  pip: true
